#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo "switch directory"
cd $DIR
echo "starting docker containers"
docker-compose up --build
echo "servers zijn up and running...  Gebruik Ctrl + C om af te sluiten"
